### ISSUE TITLE
这么好的项目，怎么会无人问津啊~~~~

### ISSUE THREAD

**Issue by MaxMax2016** [yqzhishen/opensvip#1]

**Comment by yqzhishen** [comment]
您好，感谢您的支持！项目成果目前处于公测阶段，还没有正式开始宣传。由于需求的变更，本项目在创立之初的架构可能在未来无法满足需要，因此我们未来会重写底层框架，开发更加通用强大的歌声合成工程处理接口，探索全新的调音工作流。目前本项目的日常更新以及未来框架的搭建均会在组织账号 @openvpi 下进行，届时也将欢迎更多开发者的加入，敬请关注。
由于这并不属于一个 bug report / feature request，我将关闭该 issue，抱歉。
