### ISSUE TITLE
i am confused about this tool

### ISSUE THREAD

**Issue by lvZic** [yqzhishen/opensvip#18]
I just want to get F0 truth of opencpop dataset, so what i should do by using this tool.
![image](https://github.com/yqzhishen/opensvip/assets/7788572/ff7bf5f7-ba96-4251-8dc8-0bf43fd32191)
it seems output fixed format, by importing the above format input. So the opencpop only have midi file,  should i use the mid plugin to do the converting?

**Comment by yqzhishen** [comment]
Opencpop contains raw wav files so you can simply use pitch extraction algorithms to get the f0

**Comment by lvZic** [comment]
> Opencpop contains raw wav files so you can simply use pitch extraction algorithms to get the f0

thanks for reply.
So the wav file of oencpop used to extract F0 is the human voice? not the melody. I should use the human voice to get F0. is it right?

**Comment by yqzhishen** [comment]
yes

**Comment by lvZic** [comment]
> yes

i used librosa to get F0:
y, sr = librosa.load(filename, sr=None)
f0_new = librosa.yin(y[:], fmin=librosa.note_to_hz('A1'), fmax=librosa.note_to_hz('G7'), sr=sr)
f0_new[np.isnan(f0_new)] = 0

 param['f0_seq'] = f0_new
param['f0_timestamp']  = str(2048 * 1.0 / sr)

however, the final wav file sounds weird, which means the F0 is not fit.

**Comment by yqzhishen** [comment]
See https://github.com/openvpi/DiffSinger/blob/d79ce3fe8ac8a0832202ce8fe1e48cce17e64aa6/utils/binarizer_utils.py#L12 and be careful about `f0_timestep`.

I will close this issue since it's not related to this project.
