### ISSUE TITLE
.acep格式 转换失败

### ISSUE THREAD

**Issue by NewSapporoNingyo** [yqzhishen/opensvip#3]
在转换ACE工程文件到SynthV工程时失败，程序报错信息为“解密失败：输入文件格式错误“。
已经按照https://openvpi.github.io/docs/faq.html 内的步骤排查问题，仍然无法正常转换。
使用的工程文件存放在这个目录下https://github.com/noname390/Yuhisaka_cover/tree/main/Yuhisaka_ace

**Comment by yqzhishen** [comment]
你好，经查是解密算法中 zero padding 的策略问题，将很快发布下一个版本修复此问题。如果急用，请尝试修改一下源工程的数据（例如随便加一个音符），然后再次尝试转换。谢谢！

**Comment by yqzhishen** [comment]
问题已解决，请更新插件。
